config/routes.rb
Rails.application.routes.draw do
  root to: 'item#index'
  devise_for :members, :controllers => { registrations: 'member/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/cart', to: 'cart#show'
  get '/order', to: 'order#show'
  get '/orders', to: 'order#index'
  post 'cart/add'
  post 'cart/remove'
  post 'checkout/create', to: 'checkout#create'
  get '/', to: 'item#index'
  get '/search', to: 'item#search'
  get '/item_types', to: 'item_types#index'
  post 'item/add_to_cart/:id', to: 'item#add_to_cart', as: 'add_to_cart'
  delete 'item/remove_from_cart/:id', to: 'item#remove_from_cart', as: 'remove_from_cart'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :item
  resources :item_types
  resources :game_type
  resources :rarity
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.ransackable_attributes(auth_object = nil)
    ["email", "password", "password_confirmation"]
  end
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :items, through: :cart_items

    def total
        cart_items.to_a.sum { |item| item.total}
    end

    def total_after_taxes
        cart_items.to_a.sum { |item| item.total + (item.total * ((Member.current.province.GST + Member.current.province.PST + Member.current.province.HST)/100)).round(2) }
    end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def total
    item.price * quantity
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
    has_many :items
    has_many :trades
    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :item_type
    belongs_to :rarity
    belongs_to :game_type
    has_many :cart_items
    has_many :carts, through: :cart_items
    validates :name, presence: true
    validates :price, presence: true, numericality: true
    validates :stock, presence: true, numericality: { only_integer: true }

    def self.ransackable_attributes(auth_object = nil)
        ["name", "stock", "price"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name", "stock", "price"]
      end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
    has_many :items
    validates :name, presence: true, uniqueness: true

    def self.ransackable_attributes(auth_object = nil)
        ["name"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name"]
      end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_and_belongs_to_many :items
    has_many :orders
    belongs_to :province
    validates :full_name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true
    validates :address, presence: true
    validates :province, presence: true
    validates :store_credit_available, numericality: true, allow_nil: true

    def self.current
      Thread.current[:member]
    end
    def self.current=(member)
      Thread.current[:member] = member
    end
end

app/models/member_item.rb
class MemberItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_status
    belongs_to :member
    belongs_to :item
    validates :order_number, presence: true, numericality: { only_integer: true }
    validates :is_completed, inclusion: [true, false]
    validates :price, presence: true, numericality: true
    validates :quantity, presence: true, numericality: { only_integer: true }
    validates :payment_link, presence: true, allow_nil: true
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    validates :status, presence: true, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
    attr_accessor :province_id
end

app/models/rarity.rb
class Rarity < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
    belongs_to :item_type
    belongs_to :game_type
    belongs_to :game_edition
    validates :name, presence: true
    validates :rarity, presence: true
    validates :store_credit, presence: true, numericality: true
    validates :quantity_expected, presence: true, numericality: { only_integer: true }
end

app/controllers/item_controller.rb
class ItemController < ApplicationController

    def index
        @items = Item.page(params[:page])
    end

    def show
        @item = Item.find(params[:id])
    end

    def search
        if params[:type].blank?
            if params[:search].blank?
                redirect_to '/' and return
            else
                @parameter = params[:search].downcase
                @results = Item.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
            end
        else
            if params[:search].blank?
                redirect_to '/' and return
            else
                @parameter = params[:search].downcase
                @type = params[:type]
                @results = Item.all.where("lower(name) LIKE :search AND item_type_id = :type", search: "%#{@parameter}%", type: "#{@type}")
            end
        end
    end

    def item_params
        params_require(:item).permit(:name, :stock, :price, :rarity, :item_type, :game_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/game_type_helper.rb
module GameTypeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/item_type_helper.rb
module ItemTypeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/rarity_helper.rb
module RarityHelper
end

app/views/item/index.html.erb
<div class="container">

<div class="pagetitle">
    <h1 class="display-3">Products</h1>
</div>

<%= form_tag(search_path, :method => "get") do %>
    <div class="input-group container-lg searchbar">
        <div class="input-group mb-3">
            <%= search_field_tag :search, params[:search], placeholder: 'Search by Type ', class: 'form-control' %>
        <% item_type_list = ItemType.all.map { |type| [type.name, type.id] } %>
            <%= select_tag(:type, options_for_select(item_type_list, selected: params[:type]),include_blank: true)%>
            <%= button_tag "Search", :name => nil, class:'btn btn-outline-secondary' %>
        </div>
    </div>
<% end %>

<% @items.each do |item| %>
    <div class="container text-center products-wrap">
        <div class="row products-content">
                <div class="col-sm-3 productdetails">
                    <div class="row">
                        <div class="col-sm-2">
                            <%= link_to item.name, item %>
                            <p><%= item.item_type.name %></p>
                            <p>Price: <%= item.price %></p>
                            <p>Stock: <%= item.stock %></p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-9">
                    <%= image_tag item.image %>
                </div>
        </div>
    </div>
<% end %>
<div>

<%= paginate @items %>

app/views/item/search.html.erb
<div class="container">

<div class="pagetitle">
    <h1 class="display-3">Products</h1>
    <%= link_to "Back", "/", style:"color:white" %>
</div>

<% @results.each do |item| %>
    <div class="container text-center products-wrap">
        <div class="row products-content">
                <div class="col-sm-3 productdetails">
                    <div class="row">
                        <div class="col-sm-2">
                            <%= link_to item.name, item %>
                            <p><%= item.item_type.name %></p>
                            <p>Price: <%= item.price %></p>
                            <p>Stock: <%= item.stock %></p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-9">
                    <%= image_tag item.image %>
                </div>
        </div>
    </div>
<% end %>
</div>

app/views/item/show.html.erb
<div class="container">
    <div class="pagetitle">
        <h1 class="display-3"><%= @item.name %></h1>
        <%= link_to "Back", "/", style:"color:white" %>
    </div>

    <div class="container text-center products-wrap">
        <div class="row products-content">
            <div class="col-sm-3 productdetails">
                <div class="row">
                    <div class="col-sm-3">
                        <p><%= @item.item_type.name %></p>
                        <p>Price: <%= @item.price %></p>
                        <p>Stock: <%= @item.stock %></p>
                        <p>Rarity: <%= @item.rarity.name %></p>
                         <% if member_signed_in? %>
                            <p>Add to your cart, <%= current_member.username %></p>
                            <%= form_with(url: cart_add_path) do |f| %>
                                <%= f.hidden_field :id, value: @item.id %>
                                <%= f.number_field :quantity, value: 0, max:@item.stock, min:1, class: 'searchbar' %>
                                <%= f.submit "Add to cart", class:"btn btn-outline-success", style:"margin-top:5px" %>
                           <% end %>
                        <% else %>
                              <p>Sign up to order</p>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="col-sm-9">
                <%= image_tag @item.image %>
            </div>
        </div>
   </div> 
</div>