config/routes.rb
Rails.application.routes.draw do
  root to: 'item#index'
  devise_for :members, :controllers => { registrations: 'member/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/cart', to: 'cart#show'
  get '/order', to: 'order#show'
  get '/orders', to: 'order#index'
  post 'cart/add'
  post 'cart/remove'
  post 'checkout/create', to: 'checkout#create'
  get '/', to: 'item#index'
  get '/search', to: 'item#search'
  get '/item_types', to: 'item_types#index'
  post 'item/add_to_cart/:id', to: 'item#add_to_cart', as: 'add_to_cart'
  delete 'item/remove_from_cart/:id', to: 'item#remove_from_cart', as: 'remove_from_cart'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :item
  resources :item_types
  resources :game_type
  resources :rarity
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.ransackable_attributes(auth_object = nil)
    ["email", "password", "password_confirmation"]
  end
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :items, through: :cart_items

    def total
        cart_items.to_a.sum { |item| item.total}
    end

    def total_after_taxes
        cart_items.to_a.sum { |item| item.total + (item.total * ((Member.current.province.GST + Member.current.province.PST + Member.current.province.HST)/100)).round(2) }
    end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def total
    item.price * quantity
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
    has_many :items
    has_many :trades
    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :item_type
    belongs_to :rarity
    belongs_to :game_type
    has_many :cart_items
    has_many :carts, through: :cart_items
    validates :name, presence: true
    validates :price, presence: true, numericality: true
    validates :stock, presence: true, numericality: { only_integer: true }

    def self.ransackable_attributes(auth_object = nil)
        ["name", "stock", "price"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name", "stock", "price"]
      end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
    has_many :items
    validates :name, presence: true, uniqueness: true

    def self.ransackable_attributes(auth_object = nil)
        ["name"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name"]
      end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_and_belongs_to_many :items
    has_many :orders
    belongs_to :province
    validates :full_name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true
    validates :address, presence: true
    validates :province, presence: true
    validates :store_credit_available, numericality: true, allow_nil: true

    def self.current
      Thread.current[:member]
    end
    def self.current=(member)
      Thread.current[:member] = member
    end
end

app/models/member_item.rb
class MemberItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_status
    belongs_to :member
    belongs_to :item
    validates :order_number, presence: true, numericality: { only_integer: true }
    validates :is_completed, inclusion: [true, false]
    validates :price, presence: true, numericality: true
    validates :quantity, presence: true, numericality: { only_integer: true }
    validates :payment_link, presence: true, allow_nil: true
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    validates :status, presence: true, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
    attr_accessor :province_id
end

app/models/rarity.rb
class Rarity < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
    belongs_to :item_type
    belongs_to :game_type
    belongs_to :game_edition
    validates :name, presence: true
    validates :rarity, presence: true
    validates :store_credit, presence: true, numericality: true
    validates :quantity_expected, presence: true, numericality: { only_integer: true }
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @item = Item.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_cart_item = @cart.cart_items.find_by(item_id: @item.id)
      if current_cart_item && quantity > 0
        current_cart_item.update(quantity: current_cart_item.quantity + quantity)
      else
        @cart.cart_items.create(item: @item, quantity:)
      end
        redirect_back(fallback_location: cart_path)
  end

  def remove
    CartItem.find_by(id: params[:id]).destroy
    redirect_back(fallback_location: cart_path)
    end
  end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/game_type_helper.rb
module GameTypeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/item_type_helper.rb
module ItemTypeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/rarity_helper.rb
module RarityHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
    <div class="container">
        <div class="pagetitle">
            <h1 class="display-3">Cart</h1>
        </div>
        <% if @cart.cart_items.count > 0 %>
            <div class="container text-center">
                <div class="row">
                    <div class="col-sm-12 productdetails">
                        <div class="row">
                            <div class="col-sm-10">
                            <% if member_signed_in? %>
                            These are the rate taxes for your Province: <%= current_member.province.shortname %>, <%= current_member.username %>
                                  <% if current_member.province.GST > 0 %>
                                      <p>GST: <%=current_member.province.GST %></p>
                                  <% end %>
                                  <% if current_member.province.PST > 0 %>
                                      <p>PST: <%=current_member.province.PST %></p>
                                  <% end %>
                                  <% if current_member.province.HST > 0 %>
                                    <p>HST: <%=current_member.province.HST %></p>
                                  <% end %>
                          <% end %>
                            <%= render "cart/cart_item" %>
                            <p style="padding-top:5%;">Cart Total: <%= @cart.total %></p>
                            <p>Cart Total after taxes: <%= @cart.total_after_taxes %></p>
                            <%= link_to "Checkout", order_path, data: {turbo_frame: "_top"} %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% else %>
            <div class="container text-center">
                <div class="row">
                    <div class="col-sm-12 productdetails">
                        <div class="row">
                            <div class="col-sm-10">
                                <p>Cart is empty</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/cart/_cart_item.html.erb
<% @cart.cart_items.each do |item_in_cart| %>
    <% item = item_in_cart.item %>
    <div id="<%= "cart-#{item.id}" %>">
        <div class="container text-center">
                            <p>Product: <%= item.name %> <%= item.item_type.name %></p>
                            <p>Price: <%= item.price %></p>
                            <p>Stock: <%= item.stock %></p>
                            <p>Rarity: <%= item.rarity.name %></p>
                            <%= form_with(url: cart_add_path) do |f| %>
                                <%= f.hidden_field :id, value: item.id %>
                                <%= f.number_field :quantity, value: item_in_cart.quantity, min:1, max: item.stock, class: 'searchbar' %>
                                <%= f.submit "Add to cart", class:"btn btn-outline-success", style:"margin-top:5px" %>
                            <% end %>
                            <%= form_with(url: cart_remove_path) do |f| %>
                                <%= f.hidden_field :id, value: item_in_cart.id %>
                                <%= f.submit "Delete from cart", class:"btn btn-outline-success", style:"margin-top:5px" %>
                            <% end %>
        </div>
    </div>
<% end %>

app/views/cart/show.html.erb
<%= render partial: "cart/cart" %>