config/routes.rb
Rails.application.routes.draw do
  root to: 'item#index'
  devise_for :members, :controllers => { registrations: 'member/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/cart', to: 'cart#show'
  get '/order', to: 'order#show'
  get '/orders', to: 'order#index'
  post 'cart/add'
  post 'cart/remove'
  post 'checkout/create', to: 'checkout#create'
  get '/', to: 'item#index'
  get '/search', to: 'item#search'
  get '/item_types', to: 'item_types#index'
  post 'item/add_to_cart/:id', to: 'item#add_to_cart', as: 'add_to_cart'
  delete 'item/remove_from_cart/:id', to: 'item#remove_from_cart', as: 'remove_from_cart'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :item
  resources :item_types
  resources :game_type
  resources :rarity
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.ransackable_attributes(auth_object = nil)
    ["email", "password", "password_confirmation"]
  end
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :items, through: :cart_items

    def total
        cart_items.to_a.sum { |item| item.total}
    end

    def total_after_taxes
        cart_items.to_a.sum { |item| item.total + (item.total * ((Member.current.province.GST + Member.current.province.PST + Member.current.province.HST)/100)).round(2) }
    end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def total
    item.price * quantity
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
    has_many :items
    has_many :trades
    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :item_type
    belongs_to :rarity
    belongs_to :game_type
    has_many :cart_items
    has_many :carts, through: :cart_items
    validates :name, presence: true
    validates :price, presence: true, numericality: true
    validates :stock, presence: true, numericality: { only_integer: true }

    def self.ransackable_attributes(auth_object = nil)
        ["name", "stock", "price"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name", "stock", "price"]
      end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
    has_many :items
    validates :name, presence: true, uniqueness: true

    def self.ransackable_attributes(auth_object = nil)
        ["name"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name"]
      end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_and_belongs_to_many :items
    has_many :orders
    belongs_to :province
    validates :full_name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true
    validates :address, presence: true
    validates :province, presence: true
    validates :store_credit_available, numericality: true, allow_nil: true

    def self.current
      Thread.current[:member]
    end
    def self.current=(member)
      Thread.current[:member] = member
    end
end

app/models/member_item.rb
class MemberItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_status
    belongs_to :member
    belongs_to :item
    validates :order_number, presence: true, numericality: { only_integer: true }
    validates :is_completed, inclusion: [true, false]
    validates :price, presence: true, numericality: true
    validates :quantity, presence: true, numericality: { only_integer: true }
    validates :payment_link, presence: true, allow_nil: true
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    validates :status, presence: true, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
    attr_accessor :province_id
end

app/models/rarity.rb
class Rarity < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
    belongs_to :item_type
    belongs_to :game_type
    belongs_to :game_edition
    validates :name, presence: true
    validates :rarity, presence: true
    validates :store_credit, presence: true, numericality: true
    validates :quantity_expected, presence: true, numericality: { only_integer: true }
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    before_action :create, except:[:index]
    
    def index
        @order = Order.joins(:member).where('member_id = ?', "#{current_member.id}")
    end
    
    def show
        @member_order = current_member
        @order_cart = @cart
        @cart = Cart.create
        session[:cart_id] = @cart.id
    end

    def create
        order_number = rand 1..1000000
        @cart.cart_items.each do |cart_item|
            new_order = Order.new
            new_order.is_completed = false
            new_order.price = cart_item.item.price
            new_order.member = current_member
            new_order.quantity = cart_item.quantity
            new_order.item = Item.find_by(id: cart_item.item.id)
            new_order.order_status = OrderStatus.find_by(id: 1)
            new_order.order_number = order_number
            new_order.GST = current_member.province.GST
            new_order.PST = current_member.province.PST
            new_order.HST = current_member.province.HST
            new_order.total = @cart.total
            new_order.total_with_taxes = @cart.total_after_taxes
            new_order.save
            puts new_order.save!
            @order = order_number
        end
    end

    def order_params
        params_require(:order).permit(:order_number, :is_completed, :price, :quantity, :payment_link)
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/game_type_helper.rb
module GameTypeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/item_type_helper.rb
module ItemTypeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/rarity_helper.rb
module RarityHelper
end

app/views/order/index.html.erb
<div class="container">

<div class="pagetitle">
    <h1 class="display-3">Checkout</h1>
</div>
<div class="container text-center">
    <div class="row">
        <div class="col-sm-12 productdetails">
            <div class="row">
                <div class="col-sm-10">
                                <% if @order.length > 0 %>
                                    <% @order.each do |order| %>
                                        <p><%= order.order_number %><p>
                                        <p><%= order.item.name %><p>
                                        <p>Rarity: <%= order.item.rarity.name %><p>
                                        <p>Quantity: <%= order.quantity %><p>
                                        <p>Price: <%= order.item.price %><p>
                                        <p>Order Status: <%= order.order_status.status %><p>
                                        <p>Date: <%= order.created_at %><p>
                                        <hr>
                                    <% end %>
                                <% else %>
                                    <p>No orders yet, try looking for something cool
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>

app/views/order/show.html.erb
<div class="container">

<div class="pagetitle">
    <h1 class="display-3">Checkout</h1>
</div>
<div class="container text-center">
                <div class="row">
                    <div class="col-sm-12 productdetails">
                    <div class="row">
                    <div class="col-sm-8" style="padding-left:30%; padding-bottom:10%;">
                        Your order has been saved succesfully
                    </div>
                </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <p><%= @member_order.username %>'s order</p>
                                <% total = @order_cart.total %>
                                    <% if current_member.province.GST > 0 %>
                                        <p>GST: <%=current_member.province.GST %></p>
                                        <% total = total + (total * (current_member.province.GST / 100)) %>
                                    <% end %>
                                    <% if current_member.province.PST > 0 %>
                                        <p>PST: <%=current_member.province.PST %></p>
                                        <% total = total + (total * (current_member.province.PST / 100)) %>
                                    <% end %>
                                    <% if current_member.province.HST > 0 %>
                                        <p>HST: <%=current_member.province.HST %></p>
                                        <% total = total + (total * (current_member.province.HST / 100)) %>
                                    <% end %>
                            </div>
                            <div class="col-sm-5">
                                <% @order_cart.cart_items.each do |cart| %>
                                    <p><%= cart.item.item_type.name %>: <%= cart.item.name %><p>
                                    <p>Rarity: <%= cart.item.rarity.name %><p>
                                    <p>Quantity: <%= cart.quantity %><p>
                                    <p>Price: <%= cart.item.price %><p>
                                    <hr>
                                <% end %>
                            </div>
                            <div class="col-sm-3" style="background-color: #031633; color:white; height:20%;">
                                <p>Cart Total: <%= @order_cart.total %></p>
                                <p>Cart Total after taxes: <%= @order_cart.total_after_taxes %></p>
                                <%= button_to "Pay Now", checkout_create_path, params: {order_number: @order}, data: {turbo: false} %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>