config/routes.rb
Rails.application.routes.draw do
  root to: 'item#index'
  devise_for :members, :controllers => { registrations: 'member/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/cart', to: 'cart#show'
  get '/order', to: 'order#show'
  get '/orders', to: 'order#index'
  post 'cart/add'
  post 'cart/remove'
  post 'checkout/create', to: 'checkout#create'
  get '/', to: 'item#index'
  get '/search', to: 'item#search'
  get '/item_types', to: 'item_types#index'
  post 'item/add_to_cart/:id', to: 'item#add_to_cart', as: 'add_to_cart'
  delete 'item/remove_from_cart/:id', to: 'item#remove_from_cart', as: 'remove_from_cart'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :item
  resources :item_types
  resources :game_type
  resources :rarity
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.ransackable_attributes(auth_object = nil)
    ["email", "password", "password_confirmation"]
  end
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :items, through: :cart_items

    def total
        cart_items.to_a.sum { |item| item.total}
    end

    def total_after_taxes
        cart_items.to_a.sum { |item| item.total + (item.total * ((Member.current.province.GST + Member.current.province.PST + Member.current.province.HST)/100)).round(2) }
    end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def total
    item.price * quantity
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
    has_many :items
    has_many :trades
    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :item_type
    belongs_to :rarity
    belongs_to :game_type
    has_many :cart_items
    has_many :carts, through: :cart_items
    validates :name, presence: true
    validates :price, presence: true, numericality: true
    validates :stock, presence: true, numericality: { only_integer: true }

    def self.ransackable_attributes(auth_object = nil)
        ["name", "stock", "price"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name", "stock", "price"]
      end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
    has_many :items
    validates :name, presence: true, uniqueness: true

    def self.ransackable_attributes(auth_object = nil)
        ["name"]
      end
    
      def self.ransackable_associations(auth_object = nil)
        ["name"]
      end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_and_belongs_to_many :items
    has_many :orders
    belongs_to :province
    validates :full_name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true
    validates :address, presence: true
    validates :province, presence: true
    validates :store_credit_available, numericality: true, allow_nil: true

    def self.current
      Thread.current[:member]
    end
    def self.current=(member)
      Thread.current[:member] = member
    end
end

app/models/member_item.rb
class MemberItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_status
    belongs_to :member
    belongs_to :item
    validates :order_number, presence: true, numericality: { only_integer: true }
    validates :is_completed, inclusion: [true, false]
    validates :price, presence: true, numericality: true
    validates :quantity, presence: true, numericality: { only_integer: true }
    validates :payment_link, presence: true, allow_nil: true
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    validates :status, presence: true, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
    attr_accessor :province_id
end

app/models/rarity.rb
class Rarity < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
    belongs_to :item_type
    belongs_to :game_type
    belongs_to :game_edition
    validates :name, presence: true
    validates :rarity, presence: true
    validates :store_credit, presence: true, numericality: true
    validates :quantity_expected, presence: true, numericality: { only_integer: true }
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/game_type_helper.rb
module GameTypeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/helpers/rarity_helper.rb
module RarityHelper
end

app/views/layouts/_navbar.html.erb
        <nav class="navbar navbar-expand-lg bg-body-tertiary navbar">
            <div class="container-fluid">
                <div class="expand navbar-expand">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"><%= link_to "Home", "/", class:"nav-link" %></li>        
                        <li class="nav-item"><%= link_to "Categories", item_types_path, class:"nav-link" %></li>
                        <li class="nav-item"><%= link_to 'Cart', cart_path, class:"nav-link" %></li>
                       <p class="navbar-text"> (<%= @cart.cart_items.count %>) </p>
                        <% if member_signed_in? %>
                            <span class="navbar-text" style="margin-right:5px; margin-left:15px;">Welcome Home, <%= current_member.username %></span>
                            <li class="nav-item"><%= link_to 'Show History', orders_path, class:"nav-link" %></li>
                            <li class="nav-item"><%= button_to 'Sign out', destroy_member_session_path, method: :delete, class:"btn btn-outline-success" %></li>
                        <% else %>
                        <li class="nav-item"><%= link_to 'Sign in', new_member_session_path, class:"nav-link" %></li>
                        <% end %>
                    </ul>
                </div>
                <%= image_tag("cards_icon.png", class:"imgbar") %>
           </div> 
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeMagic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="background">
    <%= render "layouts/navbar" %>
    <p class="notice" style="font-weight: bolder; text-align:center"><%= notice %></p>
    <p class="alert" style="font-weight: bolder; text-align:center"><%= alert %></p>
    <%= yield %>
  </body>
</html>